kmastock/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import edit_user_profile, add_user_profile
# UserProfilePageView,

app_name = 'accounts'

urlpatterns = [
    # previous login view
    # path('login/', views.user_login, name='login'),
    
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('profile/<profile_uuid>/', UserProfilePageView.as_view(), name='user_profile'), # profile page views
    path('profile/user/id/<user_id>/unique/id/<uuid>/', edit_user_profile, name='edit_user_profile'), # profile page views
    path('profile/user/id/<user_id>/', add_user_profile, name='add_user_profile'), # profile page views
]

kmastock/apps/category/urls.py
from django.urls import path
from .views import add_category, edit_category
from django.contrib.auth.decorators import login_required

app_name = 'category'
urlpatterns = [
    path('add/new/category/', login_required(add_category), name='add_category'),
    path('edit/category/id/<int:category_id>/', login_required(edit_category), name='edit_category'),
]

kmastock/apps/stocks/urls.py
from django.urls import path
from .views import add_stock, edit_stock


app_name = 'stocks'
urlpatterns = [
    path('add/new/stock/', add_stock,name='add_stock'),
    path('edit/stock/id/<int:stock_id>/', edit_stock,name='edit_stock'),
]

kmastock/apps/vendors/urls.py
from django.urls import path
from .views import add_vendor, edit_vendor
from django.contrib.auth.decorators import login_required

app_name = 'vendors'
urlpatterns = [
    path('add/new/vendor/', login_required(add_vendor), name='add_vendor'),
    path('edit/vendor/id/<int:vendor_id>/', login_required(edit_vendor), name='edit_vendor'),
]

kmastock/kmastock/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from apps.home.views import (frontpage, dashboard, tools,
                            change_language, test_)

from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns 


urlpatterns = [
    # # frontpage 
    # path('', frontpage, name='frontpage'), # main page means english
    path('change_language/', change_language, name='change_language'), # main page means english
    # path('', test_, name="test"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Go to this site(https://samulinatri.com/blog/django-translation/)
# the site explain it well
urlpatterns += i18n_patterns( # i18n_patterns important to handel languages
    path(_('admin/'), admin.site.urls),
    
    # for authentication
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    
    # frontpage 
    path('', frontpage, name='frontpage'), # main page means english
    # dashboard 
    path('dashboard/', dashboard, name='dashboard'),
    # Tools
    path('tools/', tools, name='tools'),
    
    
    # apps urls
    path('home/', include('apps.home.urls', namespace='home')),
    path('barcodes/', include('apps.barcodes.urls', namespace='barcodes')),
    path('category/', include('apps.category.urls', namespace='category')),
    path('clients/', include('apps.clients.urls', namespace='clients')),
    path('products/', include('apps.products.urls', namespace='products')),
    path('vendors/', include('apps.vendors.urls', namespace='vendors')),
    path('stocks/', include('apps.stocks.urls', namespace='stocks')),
    # path('', include('', namespace='')),
    # path('', include('', namespace='')),
    # path('', include('', namespace='')),
    # path('', include('', namespace='')),
    # path('', include('', namespace='')),
    # path('', include('', namespace='')),
        
    # from this site(https://samulinatri.com/blog/django-translation/)
    # put in the buttom  
    prefix_default_language=False

) 

kmastock/templates/base/css.html
{% load static %}

<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css"> -->
       
<link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">

<link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">

<link rel="icon" type="image/png" href="{% static 'favicon/favicon.ico' %}">
<!-- <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> -->
<link rel="stylesheet" href="{% static 'css/bootstrap07.min.css' %}">

<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

<link rel="stylesheet" href="{% static 'css/cloudflare-icon.min.css' %}">

<link rel="stylesheet" href="{% static 'css/style07.css' %}">
<link rel="stylesheet" href="{% static 'css/all.css' %}">

<!-- <link rel="stylesheet" href="{% static 'css/style_button.css' %}"> -->

<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->

kmastock/templates/base/js.html
{% load static %}


 <!-- scripts for VUE -->
 <script src="{% static 'js/vue.js' %}"></script>
 <!-- <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script> -->
 <!-- <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script> -->
 <!-- <script src="https://cdnjs.cloudfare.com/ajax/libs/axios/0.19.2/axios.min.js"> 
 </script>-->
 <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
 <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script> -->
 <!-- <script src="{% static 'js/popper.min.js' %}"></script> -->
 <script src="{% static 'js/jquery07.min.js' %}"></script>
 <script src="{% static 'js/popper07.min.js' %}"></script>
 <script src="{% static 'js/bootstrap07.min.js' %}"></script>
 <script src="{% static 'js/main07.js' %}"></script>

 <!-- <script src="{% static 'js/bootstrap413.min.js' %}"></script> -->

 <script src="{% static 'js/main.js' %}"></script>

 <script>

     var vue = new Vue ({
         el: '#footer-vue',
         delimiters: ['[', ']'],
         data: {
            footerTitle: ' Developed by Amr Aly ',
            image: "{% static 'img/2.png' %}",
         },
     });

 </script>

kmastock/templates/base/messages.html
 <section class="section">
            
    {% if messages %}
        {% for message in messages %}
            <article class="message is-{{ message.tags }}">
                <div class="message-body">
                    {{ message }}
                </div>
            </article>
        
        {% endfor %}
    {% endif %}
    <br>
    
</section>

kmastock/templates/base/navbar.html
{% load static %}
{% load i18n %}

<!-- new nav -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <button type="button" id="sidebarCollapse" class="button is-info">
            <i class="fa fa-bars"></i>
            <span class="sr-only">Toggle Menu</span>
        </button>
        <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fa fa-bars"></i>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav navbar-nav ml-auto">
            {% if user.is_authenticated %}
                    
                {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                        <span class="fa fa-shopping-basket"></span> {% trans 'Sales' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"> 
                        <span class="fa fa-download"></span> {% trans 'Returns' %}</a>
                    </li>
                {% endif %}
                {% if user.is_superuser %}
                    <li class="nav-item">  
                    {% get_current_language as CODE %}
                    {% if CODE == 'en-us' %}   
                        <a class="nav-link" href="/admin" target="_blank"><i class="fa fa-address-book"></i>
                            Admin Panel</a>
                    {% else %}
                        <a class="nav-link" href="/{{CODE}}/admin" target="_blank"><i class="fa fa-address-book"></i>
                            Admin Panel</a>
                    {% endif %}
                    </li>
                {% endif %}
                
                {% if user.is_authenticated and match_user %}
                    {% get_current_language as CODE %}
                    <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:edit_user_profile' profile.user_id profile.profile_uuid %}">
                        <i class="fa fa-laptop" aria-hidden="true"></i> 
                        {% trans 'Edit your profile' %}</a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'accounts:add_user_profile' request.user.id %}">
                            <i class="fa fa-laptop" aria-hidden="true"></i> 
                            {% trans 'Add new profile' %}</a>
                    </li>
                {% endif %}
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_logout' %}">
                    <span class="fa fa-sign-out-alt">
                    </span> {% trans 'Log out' %}</a>
                </li>
                
            {% else %}                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_login' %}">
                    <span class="fa fa-sign-in-alt">
                    </span> {% trans 'Login' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_signup' %}">
                    <span class="fa fa-registered">
                    </span> {% trans 'Register' %}</a>
                </li>
            {% endif %}
                <!--  -->
            <!-- {% get_current_language as CODE %}
            {% if user.is_authenticated and user.is_superuser %}
                <li class="nav-item">  
                {% if CODE == 'en-us' %}   
                    <a class="nav-link" href="/admin" target="_blank"><i class="fa fa-address-book"></i>
                        Admin Panel</a>
                {% else %}
                    <a class="nav-link" href="/{{CODE}}/admin" target="_blank"><i class="fa fa-address-book"></i>
                        Admin Panel</a>
                {% endif %}
                </li>
            {% endif %} -->
            </ul>
        </div>
    </div>
</nav>


<!-- <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <a class="navbar-brand" href="/">KMASTORE </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/dashboard">
                        {% trans 'Dashboard' %}</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#" class="navbar-item">{% trans "Add New Product" %}</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#" class="navbar-item">
                        {% trans "Active Products" %}</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#" class="navbar-item">
                        {% trans "Out Of Stock" %}</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% trans 'Stock' %}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="userMenu">
                    <a class="dropdown-item" href="{% url 'stocks:add_stock' %}">{% trans 'Add New Stock' %}</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        {% trans 'Edit Stock' %}</a>
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home:tools' %}" class="navbar-item">
                        {% trans "Tools" %}</a>
                </li>

            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% trans 'Wellcome' %}: {{ user.username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="userMenu">
                    <a class="dropdown-item" href="#{% url 'account_change_password' %}">
                        {% trans 'Change password' %}</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'account_logout' %}" style="color: red;">
                        {% trans 'Log out' %}</a>
                    </div>
                </li>
            
            </ul>
        {% else %}
            <form class="form-inline ml-auto">
            <a href="{% url 'account_login' %}" class="button  is-info">{% trans 'Log in' %}</a>&nbsp;&nbsp;
            <a href="{% url 'account_signup' %}" class="button is-secondary">{% trans 'Sign up' %}</a>
            </form>

        {% endif %}
        
        {% if user.is_authenticated %}    
        <ul class="navbar-nav ml-auto">
            <form action="{% url 'change_language' %}" method="post" id="lang">
                {% csrf_token %}
                <select name="language" class="form-control" form="lang" onchange="form.submit()" id="myDropdown">   
                    <option selected value="">{% trans 'Choose Language' %}</option>       
                    {% get_available_languages as LANGUAGES %}
                    {% for language in LANGUAGES %}
                    <option value="{{ language.0 }}" {% if language.0 == LANGUAGE_CODE %} selected {% endif %}>
                        {{ language.0|language_name_local }} 
                        ({{ language.0 }})
                    </option>
                    {% endfor %}
                </select>
                <input type="hidden" value="Change">
            </form>
        </ul>
        {% endif %}
    </div>
  </nav> -->

{% block scripts %}
  <script>
    // var x = document.getElementById("myDropdown");
    // x.selectedIndex = -1;
    // document.getElementById("myDropdown").selectedIndex = -1;
    // document.getElementsByName("language").selectedIndex = -1;
  </script>
{% endblock %}

kmastock/templates/base/search_bar.html
{% load i18n %}
{% url 'account_login' as login %}
{% url 'account_signup' as signup %}


{% if request.path == '/' or request.path == login or request.path == signup  %}
    
{% else %}
    <!-- div for searh events date -->
    <div class="align-content-center" style="background-color:transparent; height: 10%; width: 100%; margin: 30px;
    padding: 10px; border-style: outset; border-radius: 20px; border-color: #aab5af; box-shadow: 2px 2px 4px 4px darkgray;" id="search-div" name="mydiv">
        <form class="form-inline mt-2 mt-md-0" method="GET" action="/">
            <input class="form-control mr-sm-2" type="text" name='st' placeholder="{% trans 'find product by id' %}" value="{{request.GET.st}}" aria-label="Search">
            <input class="form-control mr-sm-2" type="text" name='bar' placeholder="{% trans 'find product by barcode' %}" value="{{request.GET.bar}}" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
        </form>
    </div>

{% endif %}

kmastock/templates/base/sidebar.html
{% load i18n %}
{% load static %}


<nav id="sidebar" class="active">
    <h1><a href="/" class="logo">KMA Store</a></h1>
    
    <ul class="list-unstyled components mb-5">
    {% if user.is_authenticated %}
        <li class="active">
            <a href="#userSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                <span class="fa fa-user"></span>
                {% trans 'Wellcome' %}: {{ user.username }}
            </a>
            <ul class="collapse list-unstyled" id="userSubmenu">
                <li>
                    <a href="/dashboard"><span class="fa fa-laptop"></span>
                    {% trans 'Dashboard' %}</a>
                </li>

                {% if user.is_staff %}
                <li>
                    <a href="#">
                        <span class="fa fa-cubes"></span>
                        {% trans 'Created Products' %}</a>
                </li>
                <li>
                    <a href="#"> 
                        <span class="fas fa-battery-full"></span>
                        {% trans 'Created Stores' %}</a>
                </li>
                <li>
                    <a href="#"> 
                        <span class="fas fa-user-plus"></span>
                        {% trans 'Created Vendors' %}</a>
                </li>
                {% endif %}
                <li>
                    <a href="{% url 'account_logout' %}">
                    <i class="fa fa-sign-out-alt" aria-hidden="true">
                    </i> {% trans 'Log out' %}</a>
                </li>
            </ul>              
        </li>
    {% endif %}
        <!-- <li class="active">
            <a href="#">
            <span class="fa fa-home"></span> Home</a>
        </li> -->
    
    {% if user.is_staff %}  
        <li>
            <a href="#productSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                <span class="fa fa-cubes"></span>{% trans 'Products' %}</a>
            <ul class="collapse list-unstyled" id="productSubmenu">
                <li>
                <a href="{% url 'products:add_product' %}">
                    <span class="fa fa-plus-square" aria-hidden="true">
                    </span>{% trans 'Add New Product' %}</a>
                </li>
                <li>
                    <a href="#"><span class="fa fa-pen-square" aria-hidden="true">
                    </span>{% trans 'Edit Product' %}</a>
                </li>
                <li>
                    <a href="#">
                    <span class="fa fa-battery-empty"></span>
                    {% trans 'Out Of Stock' %}</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#stockSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
            <span class="fa fa-bank"></span> {% trans 'Stores' %}</a>
            <ul class="collapse list-unstyled" id="stockSubmenu">
                <li>
                    <a href="{% url 'stocks:add_stock' %}">
                        <span class="fa fa-plus-square" aria-hidden="true">
                        </span> {% trans 'Add New Store' %}</a>
                </li>
                <li>
                    <a href="#"><span class="fa fa-pencil-square-o">
                    </span>
                    {% trans 'Edit Store' %} </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#vendorSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
            <span class="fa fa-group"></span> {% trans 'Vendors' %}</a>
            <ul class="collapse list-unstyled" id="vendorSubmenu">
                <li>
                    <a href="{% url 'vendors:add_vendor' %}">
                        <span class="fa fa-plus-square" aria-hidden="true">
                        </span> {% trans 'Add New Vendor' %}</a>
                </li>
                <li>
                    <a href="#"><span class="fa fa-pencil-square-o">
                    </span>
                    {% trans 'Edit Vendor' %} </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#categorySubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
            <span class="fa fa-coffee"></span> {% trans 'Categories' %}</a>
            <ul class="collapse list-unstyled" id="categorySubmenu">
                <li>
                    <a href="{% url 'category:add_category' %}">
                        <span class="fa fa-plus-square" aria-hidden="true">
                        </span> {% trans 'Add New Category' %}</a>
                </li>
                <li>
                    <a href="#"><span class="fa fa-pencil-square-o">
                    </span>
                    {% trans 'Edit Category' %} </a>
                </li>
            </ul>
        </li>
    {% endif %}
        <li>
            <a href="#">
                <span class="fa fa-cogs"></span> 
                {% trans 'Services' %}
            </a>
        </li>
        <li>
            <a href="#"><span class="fa fa-paper-plane">
            </span> {% trans 'Contacts' %}</a>
        </li>
        
        <li>
            <form action="{% url 'change_language' %}" method="post" id="lang">
                {% csrf_token %}
                <select name="language" class="form-control" form="lang" onchange="form.submit()" id="myDropdown">   
                    <option selected value="">{% trans 'Choose Language' %}</option>       
                    {% get_available_languages as LANGUAGES %}
                    {% for language in LANGUAGES %}
                    <option value="{{ language.0 }}" {% if language.0 == LANGUAGE_CODE %} selected {% endif %}>
                        {{ language.0|language_name_local }} 
                        ({{ language.0 }})
                    </option>
                    {% endfor %}
                </select>
                <input type="hidden" value="Change">
            </form>
        </li>
        
    </ul>

<div class="footer" style="background-color: transparent;">
    <p>
        <h6>
            Copyright &copy;{% now 'Y' %} 
            {% trans 'All rights reserved,' %} 
            {% trans 'This software is made with by Eng. Amr Aly' %}
            <!-- num1 = {{var}} : {{attr1}} , 
            num2 = {{num2}} : {{attr2}} -->
        </h6>
    </p>
</div>
</nav>

kmastock/templates/base/tools_navbar.html
<!-- {% extends 'base.html' %} -->
{% load static %}
{% load i18n %}

<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <a class="navbar-brand" href="/">KMASTORE </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
       
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/dashboard">
                        {% trans 'Dashboard' %}</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% trans 'Stock' %}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="userMenu">
                    <a class="dropdown-item" href="{% url 'stocks:add_stock' %}">{% trans 'Add New Stock' %}</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#{% url 'stocks:edit_stock' id.stock_id %}">
                        {% trans 'Edit Stock' %}</a>
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#" class="navbar-item">{% trans "Add New Stock" %}</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#" class="navbar-item">
                        {% trans "Active Products" %}</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#" class="navbar-item">
                        {% trans "Out Of Stock" %}</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#" class="navbar-item">
                        {% trans "Your Created Products" %}</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% trans 'Wellcome' %}: {{ user.username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="userMenu">
                    <a class="dropdown-item" href="#{% url 'account_change_password' %}">
                        {% trans 'Change password' %}</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'account_logout' %}" style="color: red;">
                        {% trans 'Log out' %}</a>
                    </div>
                </li>
            </ul>

            <form class="form-inline ml-auto">
            <a href="{% url 'account_login' %}" class="button  is-info">{% trans 'Log in' %}</a>&nbsp;&nbsp;
            <a href="{% url 'account_signup' %}" class="button is-secondary">{% trans 'Sign up' %}</a>
            </form>
             

    </div>
  </nav>

{% block scripts %}
  <script>
    // var x = document.getElementById("myDropdown");
    // x.selectedIndex = -1;
    // document.getElementById("myDropdown").selectedIndex = -1;
    // document.getElementsByName("language").selectedIndex = -1;
  </script>
{% endblock %}