kmastock/apps/barcodes/urls.py
from django.urls import path
from .views import generate_barcode, read_barcode

app_name = 'barcodes'
urlpatterns = [
    path('generate/photo/', generate_barcode, name='generate_barcode'),
    path('read/photo/', read_barcode, name='read_barcode'),
]

kmastock/kmastock/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from apps.home.views import (frontpage, dashboard, tools,
                            change_language, test_)

from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns 


urlpatterns = [
    # # frontpage 
    # path('', frontpage, name='frontpage'), # main page means english
    path('change_language/', change_language, name='change_language'), # main page means english
    # path('', test_, name="test"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Go to this site(https://samulinatri.com/blog/django-translation/)
# the site explain it well
urlpatterns += i18n_patterns( # i18n_patterns important to handel languages
    path(_('admin/'), admin.site.urls),
    
    # for authentication
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    
    # frontpage 
    path('', frontpage, name='frontpage'), # main page means english
    # dashboard 
    path('dashboard/', dashboard, name='dashboard'),
    # Tools
    path('tools/', tools, name='tools'),
    
    
    # apps urls
    path('home/', include('apps.home.urls', namespace='home')),
    path('barcodes/', include('apps.barcodes.urls', namespace='barcodes')),
    path('category/', include('apps.category.urls', namespace='category')),
    path('clients/', include('apps.clients.urls', namespace='clients')),
    path('products/', include('apps.products.urls', namespace='products')),
    path('vendors/', include('apps.vendors.urls', namespace='vendors')),
    path('stocks/', include('apps.stocks.urls', namespace='stocks')),
    # path('', include('', namespace='')),
    # path('', include('', namespace='')),
    # path('', include('', namespace='')),
    # path('', include('', namespace='')),
    # path('', include('', namespace='')),
    # path('', include('', namespace='')),
        
    # from this site(https://samulinatri.com/blog/django-translation/)
    # put in the buttom  
    prefix_default_language=False

) 

kmastock/apps/barcodes/views.py
from django.shortcuts import render,reverse,redirect
from django.http import HttpResponseRedirect
from django.contrib import messages
import os
import pyqrcode
from pyzbar.pyzbar import decode
from PIL import Image
# Create your views here.

def generate_barcode(request): # Done Good Job man
    # Generate QR Code
    barcode_value = request.GET.get('code')
    if barcode_value == None:
        messages.success(request, 'Create barcode without value is not valid')
        # qr = pyqrcode.create("12345")
        # qr.png('barcode_12345.png', scale=10)
    elif barcode_value != None:
        qr = pyqrcode.create(barcode_value)
        file_path = 'D:\Django\projects\stock\mybarcode\\barcode_' + str(barcode_value) + '_.png'
        if not os.path.exists(file_path):
            qr.png('D:\Django\projects\stock\mybarcode\\barcode_' + str(barcode_value) + '_.png', scale=10)
            messages.success(request, 'Create barcode completed with name '+ '(barcode_' + str(barcode_value) + '_.png)', extra_tags='Creation Done')
        else:
            messages.success(request, 'Barcode is already exists')
            return HttpResponseRedirect(reverse('barcodes:generate_barcode'))
    return render(request, 'barcodes/generate_barcode.html', {'value': barcode_value})

####
def read_barcode(request):
    # Read QR Code
    reader = request.GET.get('reader')
    result = '' #request.GET.get('barcode')
    file_path = str(reader) 
    if reader == None or reader == '':
        messages.success(request, 'It\'s not valid')
        # d = decode(Image.open('D:\Django\projects\stock\mybarcode\\barcode_Ecc_.png'))
        # result = d[0].data.decode('ascii')
    elif not os.path.exists(file_path):
        messages.success(request, 'File path is not correct')
    else: 
        d = decode(Image.open(reader))
        result = d[0].data.decode('ascii')
        # print(result)
    context = {'code': result,}

    return render(request, 'barcodes/read_barcode.html', context)

kmastock/apps/barcodes/templates/barcodes/generate_barcode.html
{% extends 'base.html' %}
<!-- {% load static %} -->

{% block content %}

<form class="form-inline mt-2 mt-md-0" method="GET" action="{% url 'barcodes:generate_barcode' %}">

    <input class="form-control mr-sm-2" type="text" name='code' value="{{request.GET.code}}"  placeholder="write barcode number.." aria-label="Search">

    <button class="btn btn-secondary my-2 my-sm-0" type="submit">
        Submit
    </button>
</form>
<br>

<input class="form-control mr-sm-2" type="text" name='barcode' value='{{ value }}'  placeholder="barcode will appear here...." aria-label="Search">
<br> 

{% endblock  %}

kmastock/apps/barcodes/templates/barcodes/read_barcode.html
{% extends 'base.html' %}
<!-- {% load static %} -->

{% block content %}
<!-- {{ code }} -->
<form class="form-inline mt-2 mt-md-0" method="GET" action="{% url 'barcodes:read_barcode' %}">

    <input class="form-control mr-sm-2" type="text" name='reader' value="{{request.GET.reader}}"  placeholder="write barcode path" aria-label="Search">

    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Load Path</button>
</form>
<br>
<br>

<input class="form-control mr-sm-2" type="text" name='barcode' value='{{ code }}'  placeholder="barcode will appear here...." aria-label="Search">
<br>
<!-- {{ code }} -->


{% endblock  %}